---
abstract: 'Messing with PostgreSQL network traffic'
author:
  - 'Jehan-Guillaume de Rorthais <jgdr@dalibo.com>'
  - 'Nicolas Thauvin <nicolas.thauvin@dalibo.com>'
  - 'Guillaume Lelarge <guillaume.lelarge@dalibo.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: pgShark
provides:
  pgShark:
    file: lib/pgShark.pm
    version: 0.2
  pgShark::protocol_2:
    file: lib/pgShark/protocol_2.pm
    version: 0.2
  pgShark::protocol_3:
    file: lib/pgShark/protocol_3.pm
    version: 0.2
requires:
  Digest::MD5: 0
  Net::Pcap: 0
  perl: v5.8.0
resources:
  bugtracker: https://github.com/dalibo/pgshark/issues
  homepage: https://github.com/dalibo/pgshark
  license: http://opensource.org/licenses/bsd-license.php
  repository: https://github.com/dalibo/pgshark
version: 0.2
