---
abstract: 'Messing with PostgreSQL network traffic'
author:
  - 'Jehan-Guillaume (ioguix) de Rorthais <jgdr@dalibo.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: pgShark
provides:
  pgShark:
    file: lib/pgShark.pm
    version: 0.1
  pgShark::Utils:
    file: lib/pgShark/Utils.pm
    version: 0.1
requires:
  Digest::MD5: 0
  Net::Pcap: 0
  perl: v5.8.0
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: 0.1
